# E-Commerce Churn — Preprocessing & Feature Engineering

## Steps completed:
- Loaded raw e-commerce churn dataset
- Filled missing numeric values using median imputation
- Engineered four new churn-related features:
  - is_new_customer
  - is_inactive
  - is_high_cashback
  - high_risk
- Encoded all categorical columns using LabelEncoder
- Split dataset into X (features) and y (target)
- Performed stratified train-test split
- Applied StandardScaler for feature normalization
- Saved processed dataset for model training

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import os
os.getcwd()

'C:\\Users\\Varsha'

In [4]:
df=pd.read_excel(r"C:\Users\Varsha\Downloads\archive\E Commerce Dataset.xlsx")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,Data,Variable,Discerption
1,NaN,E Comm,CustomerID,Unique customer ID
2,NaN,E Comm,Churn,Churn Flag
3,NaN,E Comm,Tenure,Tenure of customer in organization
4,NaN,E Comm,PreferredLoginDevice,Preferred login device of customer

In [5]:
df.shape

(21, 4)

In [7]:
excel_file = pd.ExcelFile(r"C:\Users\Varsha\Downloads\archive\E Commerce Dataset.xlsx")
excel_file.sheet_names

['Data Dict', 'E Comm']

In [8]:
df=pd.read_excel(r"C:\Users\Varsha\Downloads\archive\E Commerce Dataset.xlsx", sheet_name='E Comm')
df.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [11]:
import os

matches = []

for root, dirs, files in os.walk(r"C:\Users\Varsha"):
    for file in files:
        if "clean" in file.lower() or "processed" in file.lower() or "ecommerce" in file.lower():
            matches.append(os.path.join(root, file))

matches[:20]

['C:\\Users\\Varsha\\.m2\\repository\\org\\apache\\maven\\plugins\\maven-clean-plugin\\3.2.0\\maven-clean-plugin-3.2.0.jar',
 'C:\\Users\\Varsha\\.m2\\repository\\org\\apache\\maven\\plugins\\maven-clean-plugin\\3.2.0\\maven-clean-plugin-3.2.0.jar.sha1',
 'C:\\Users\\Varsha\\.m2\\repository\\org\\apache\\maven\\plugins\\maven-clean-plugin\\3.5.0\\maven-clean-plugin-3.5.0.jar',
 'C:\\Users\\Varsha\\.m2\\repository\\org\\apache\\maven\\plugins\\maven-clean-plugin\\3.5.0\\maven-clean-plugin-3.5.0.jar.sha1',
 'C:\\Users\\Varsha\\.m2\\repository\\org\\apache\\maven\\plugins\\maven-clean-plugin\\3.5.0\\maven-clean-plugin-3.5.0.pom',
 'C:\\Users\\Varsha\\.m2\\repository\\org\\apache\\maven\\plugins\\maven-clean-plugin\\3.5.0\\maven-clean-plugin-3.5.0.pom.sha1',
 'C:\\Users\\Varsha\\.verdent\\skills\\pptx\\scripts\\internals\\cleanup.py',
 'C:\\Users\\Varsha\\.vscode\\extensions\\redhat.java-1.50.0-win32-x64\\document\\_java.learnMoreAboutCleanUps.md',
 'C:\\Users\\Varsha\\.vscode\\extensions\\redhat.java-1.54.0-win32-x64\\document\\_java.learnMoreAboutCleanUps.md',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\anaconda_project\\internal\\cli\\clean.py',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\anaconda_project\\internal\\cli\\test\\test_clean.py',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\anaconda_project\\internal\\cli\\test\\__pycache__\\test_clean.cpython-313.pyc',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\anaconda_project\\internal\\cli\\__pycache__\\clean.cpython-313.pyc',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\conda\\cli\\main_clean.py',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\conda\\cli\\__pycache__\\main_clean.cpython-313.pyc',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\imblearn\\under_sampling\\_prototype_selection\\_neighbourhood_cleaning_rule.py',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\imblearn\\under_sampling\\_prototype_selection\\tests\\test_neighbourhood_cleaning_rule.py',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\imblearn\\under_sampling\\_prototype_selection\\tests\\__pycache__\\test_neighbourhood_cleaning_rule.cpython-313.pyc',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\imblearn\\under_sampling\\_prototype_selection\\__pycache__\\_neighbourhood_cleaning_rule.cpython-313.pyc',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\jedi\\third_party\\typeshed\\stdlib\\2\\distutils\\command\\clean.pyi']

In [12]:
import os

excel_csv_files = []

for root, dirs, files in os.walk(r"C:\Users\Varsha"):
    for file in files:
        if file.endswith('.csv') or file.endswith('.xlsx'):
            excel_csv_files.append(os.path.join(root, file))

excel_csv_files[:50]

['C:\\Users\\Varsha\\.spyder-py3\\Book1.csv',
 'C:\\Users\\Varsha\\.spyder-py3\\Book1.csv.xlsx',
 'C:\\Users\\Varsha\\.spyder-py3\\Book2.csv',
 'C:\\Users\\Varsha\\.vscode\\extensions\\github.copilot-1.388.0\\dist\\node_modules\\@vscode\\codicons\\dist\\codicon.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\coordinates\\tests\\accuracy\\data\\fk4_no_e_fk4.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\coordinates\\tests\\accuracy\\data\\fk4_no_e_fk5.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\coordinates\\tests\\accuracy\\data\\galactic_fk4.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\coordinates\\tests\\accuracy\\data\\icrs_fk5.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\io\\ascii\\tests\\data\\simple_csv.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\io\\ascii\\tests\\data\\simple_csv_missing.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\timeseries\\tests\\data\\binned.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\astropy\\timeseries\\tests\\data\\sampled.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\datashader\\examples\\data\\.data_stubs\\nyc_taxi.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\holoviews\\examples\\assets\\emoji_embeddings.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\holoviews\\examples\\assets\\energy.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\holoviews\\examples\\assets\\fb_edges.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\holoviews\\examples\\assets\\fb_nodes.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\holoviews\\examples\\assets\\station_info.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\hvplot\\data\\crime.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\matplotlib\\mpl-data\\sample_data\\data_x_x2_x3.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\matplotlib\\mpl-data\\sample_data\\msft.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\matplotlib\\mpl-data\\sample_data\\Stocks.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\mt19937-testset-1.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\mt19937-testset-2.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\pcg64-testset-1.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\pcg64-testset-2.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\pcg64dxsm-testset-1.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\pcg64dxsm-testset-2.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\philox-testset-1.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\philox-testset-2.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\sfc64-testset-1.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\random\\tests\\data\\sfc64-testset-2.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-arccos.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-arccosh.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-arcsin.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-arcsinh.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-arctan.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-arctanh.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-cbrt.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-cos.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-cosh.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-exp.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-exp2.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-expm1.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-log.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-log10.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-log1p.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-log2.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-sin.csv',
 'C:\\Users\\Varsha\\anaconda3\\Lib\\site-packages\\numpy\\_core\\tests\\data\\umath-validation-set-sinh.csv']

In [13]:
df.isnull().sum()

CustomerID                       0
Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64

In [14]:
num_cols=df.select_dtypes(include='number').columns
num_cols

Index(['CustomerID', 'Churn', 'Tenure', 'CityTier', 'WarehouseToHome',
       'HourSpendOnApp', 'NumberOfDeviceRegistered', 'SatisfactionScore',
       'NumberOfAddress', 'Complain', 'OrderAmountHikeFromlastYear',
       'CouponUsed', 'OrderCount', 'DaySinceLastOrder', 'CashbackAmount'],
      dtype='str')

In [15]:
df[num_cols]=df[num_cols].fillna(df[num_cols].median())

In [16]:
df.isnull().sum()

CustomerID                     0
Churn                          0
Tenure                         0
PreferredLoginDevice           0
CityTier                       0
WarehouseToHome                0
PreferredPaymentMode           0
Gender                         0
HourSpendOnApp                 0
NumberOfDeviceRegistered       0
PreferedOrderCat               0
SatisfactionScore              0
MaritalStatus                  0
NumberOfAddress                0
Complain                       0
OrderAmountHikeFromlastYear    0
CouponUsed                     0
OrderCount                     0
DaySinceLastOrder              0
CashbackAmount                 0
dtype: int64

In [17]:
df['is_new_customer']=(df['Tenure'] < 3).astype(int)

In [18]:
df[['Tenure','is_new_customer']].head(10)

   Tenure  is_new_customer
0     4.0                0
1     9.0                0
2     9.0                0
3     0.0                1
4     0.0                1
5     0.0                1
6     9.0                0
7     9.0                0
8    13.0                0
9     9.0                0

In [19]:
df['is_inactive']=(df['DaySinceLastOrder'] > 20).astype(int)

In [22]:
df[['DaySinceLastOrder','is_inactive']].head(10)

   DaySinceLastOrder  is_inactive
0                5.0            0
1                0.0            0
2                3.0            0
3                3.0            0
4                3.0            0
5                7.0            0
6                0.0            0
7                0.0            0
8                2.0            0
9                1.0            0

In [23]:
df.groupby('is_inactive')['Churn'].mean()

is_inactive
0    0.168296
1    0.333333
Name: Churn, dtype: float64

In [24]:
df['is_high_cashback']=(df['CashbackAmount']>200).astype(int)

In [25]:
df[['CashbackAmount','is_high_cashback']].head(10)

   CashbackAmount  is_high_cashback
0          159.93                 0
1          120.90                 0
2          120.28                 0
3          134.07                 0
4          129.60                 0
5          139.19                 0
6          120.86                 0
7          122.93                 0
8          126.83                 0
9          122.93                 0

In [26]:
df.groupby('is_high_cashback')['Churn'].mean()

is_high_cashback
0    0.188066
1    0.104308
Name: Churn, dtype: float64

In [36]:
df['high_risk'] = ((df['Complain'] == 1) & (df['DaySinceLastOrder'] > 15)).astype(int)
print("created")

created

In [37]:
'high_risk' in df.columns

True

In [38]:
df.columns.tolist()[-5:]

['is_new_customer',
 'is_inactive',
 'is_high_cashback',
 'high-risk',
 'high_risk']

In [39]:
df.drop('high-risk', axis=1, inplace=True)

In [40]:
df.columns.tolist()[-5:]

['CashbackAmount',
 'is_new_customer',
 'is_inactive',
 'is_high_cashback',
 'high_risk']

In [41]:
cat_cols=df.select_dtypes(include='object').columns
cat_cols

C:\Users\Varsha\AppData\Local\Temp\ipykernel_28052\746331585.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols=df.select_dtypes(include='object').columns

Index(['PreferredLoginDevice', 'PreferredPaymentMode', 'Gender',
       'PreferedOrderCat', 'MaritalStatus'],
      dtype='str')

In [42]:
le=LabelEncoder()
for col in cat_cols:
    df[col]=le.fit_transform(df[col])

In [43]:
df.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,...,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount,is_new_customer,is_inactive,is_high_cashback,high_risk
0,50001,1,4.0,1,3,6.0,4,0,3.0,3,...,1,11.0,1.0,1.0,5.0,159.93,0,0,0,0
1,50002,1,9.0,2,1,8.0,6,1,3.0,4,...,1,15.0,0.0,1.0,0.0,120.90,0,0,0,0
2,50003,1,9.0,2,1,30.0,4,1,2.0,4,...,1,14.0,0.0,1.0,3.0,120.28,0,0,0,0
3,50004,1,0.0,2,3,15.0,4,1,2.0,4,...,0,23.0,0.0,1.0,3.0,134.07,1,0,0,0
4,50005,1,0.0,2,1,12.0,0,1,3.0,3,...,0,11.0,1.0,1.0,3.0,129.60,1,0,0,0

In [44]:
df.dtypes

CustomerID                       int64
Churn                            int64
Tenure                         float64
PreferredLoginDevice             int64
CityTier                         int64
WarehouseToHome                float64
PreferredPaymentMode             int64
Gender                           int64
HourSpendOnApp                 float64
NumberOfDeviceRegistered         int64
PreferedOrderCat                 int64
SatisfactionScore                int64
MaritalStatus                    int64
NumberOfAddress                  int64
Complain                         int64
OrderAmountHikeFromlastYear    float64
CouponUsed                     float64
OrderCount                     float64
DaySinceLastOrder              float64
CashbackAmount                 float64
is_new_customer                  int64
is_inactive                      int64
is_high_cashback                 int64
high_risk                        int64
dtype: object

In [45]:
X=df.drop('Churn',axis=1)
y=df['Churn']

In [46]:
X.shape, y.shape

((5630, 23), (5630,))

In [52]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [55]:
X_train.shape, X_test.shape

((4504, 23), (1126, 23))

In [56]:
from sklearn.preprocessing import StandardScaler

In [57]:
scaler=StandardScaler()

In [58]:
X_train=scaler.fit_transform(X_train)

In [59]:
X_test=scaler.transform(X_test)

In [60]:
df.to_csv(r"C:\Users\Varsha\Downloads\churn_processed.csv", index=False)

In [61]:
print("Saved! Shape:", df.shape)
print("Columns:", df.columns.tolist())

Saved! Shape: (5630, 24)
Columns: ['CustomerID', 'Churn', 'Tenure', 'PreferredLoginDevice', 'CityTier', 'WarehouseToHome', 'PreferredPaymentMode', 'Gender', 'HourSpendOnApp', 'NumberOfDeviceRegistered', 'PreferedOrderCat', 'SatisfactionScore', 'MaritalStatus', 'NumberOfAddress', 'Complain', 'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount', 'DaySinceLastOrder', 'CashbackAmount', 'is_new_customer', 'is_inactive', 'is_high_cashback', 'high_risk']